### PR TITLE
light and dark mode

### PR DESCRIPTION
**Pull request by theashu02**
@Rutuj-Runwal kindly review my PR.

### CODE REVIEW

**Comment by theashu02** [comment]
@Rutuj-Runwal kindly review my PR #5 , under hacktoberfest 2022.

**Comment by theashu02** [comment]
Screenshot (18)
Screenshot (17)
Screenshot (14)
Screenshot (13)

**Comment by Rutuj-Runwal** [comment]
Can you share a video of the functionality and scrolling through the website

**Comment by theashu02** [comment]
RR_Adblocker___Fast_Lightweight_Effective_Adblocker_-_Google_Chrome_2022-10-10_15-45-02_AdobeExpress

**Comment by Rutuj-Runwal** [comment]
> RR_Adblocker___Fast_Lightweight_Effective_Adblocker_-_Google_Chrome_2022-10-10_15-45-02_AdobeExpress [ RR_Adblocker___Fast_Lightweight_Effective_Adblocker_-_Google_Chrome_2022-10-10_15-45-02_AdobeExpress ](https://user-images.githubusercontent.com/100701424/194845509-a632de49-6097-4b1b-993f-34c913f21205.gif) [ ](https://user-images.githubusercontent.com/100701424/194845509-a632de49-6097-4b1b-993f-34c913f21205.gif)

Your css seems to have broken the image size on the right

Check with the actual website and compare accordingly: https://rutuj-runwal.github.io/RRAdblocker/

**Comment by theashu02** [comment]
I close this PR and send new PR request that's my mistake.

**Comment by Rutuj-Runwal** [comment]
Thank you for your contribution

**Pull request closed without merging**
