### PR TITLE
Newfooter updated

### PR DESCRIPTION
**Pull request by raghav1482**
@Rutuj-Runwal updated the footer . kindly review my PR

### CODE REVIEW

**Comment by raghav1482** [comment]
@Rutuj-Runwal Kindly review my PR#18.

**Review by Rutuj-Runwal — CHANGES_REQUESTED** [review]
You have removed the font awesome heart icon. It had a beat animation

Check the current website and do add it again
Check here: https://rutuj-runwal.github.io/RRAdblocker/

Rest everything is fine at best

**Comment by Rutuj-Runwal** [comment]
Look this is a single page website and The footer is still more or less the same as compared to the already existing one hence it makes this one redundant.

Thank you for your interest and efforts, you can focus on improving website responsiveness or other open issues
Closing the PR

**Comment by raghav1482** [comment]
@Rutuj-Runwal I have added the heart icon plzz review.

**Pull request closed without merging**
