### PR TITLE
fixed responsivess bug & added alt txt to imgs

### LINKED ISSUE #17: Fix bug : mobile responsiveness skewed
I noticed your site is having a responsiveness issue and was hoping I could take on this, under #hacktoberfest.
Screenshot (39)

### PR DESCRIPTION
**Pull request by Zeuhz-Droid**
Done.
Closes #17
previously....
Screenshot (40)

NOW.
Screenshot (54)

### CODE REVIEW

**Review by Rutuj-Runwal — COMMENTED** [review]
Good work,
Can you share screenshots of desktop mode as well?

**Comment by Zeuhz-Droid** [comment]
okay on it

**Comment by Zeuhz-Droid** [comment]
Here it is.
Screenshot (63)

**Comment by Rutuj-Runwal** [comment]
Nicely done👍🏻

**Pull request merged**
